#!/usr/bin/env python

from pysty import Pysty, Config


def main():

    cfg = Config()
    cfg.parse()
    cfg.save()

    cfg = Config()  # XXX: This is a quick hack to make bools work
    cfg.parse()

    pysty = Pysty(cfg)
    pysty.loop()


if __name__ == '__main__':
    main()


